export enum MenuId {
    Cast = "cast",
    CastMedia = "cast_media",
    Whitelist = "whitelist",
    WhitelistRecommended = "whitelist_recommended",
    WhitelistSeparator = "whitelist_separator",
    WhitelistSearch = "whitelist_search",
    WhitelistPath = "whitelist_path",
    WhitelistWildcardProtocol = "whitelist_wildcard_protocol",
    WhitelistWildcardSubdomain = "whitelist_wildcard_subdomain",
    WhitelistWildcardProtocolAndSubdomain = "whitelist_wildcard_protocol_and_subdomain",
    PopupCast = "popup_cast",
    PopupStop = "popup_stop",
    PopupMediaSeparator = "popup_media_separator",
    PopupMediaPlayPause = "popup_media_play_pause",
    PopupMediaMute = "popup_media_mute",
    PopupMediaSkipPrevious = "popup_media_skip_previous",
    PopupMediaSkipNext = "popup_media_skip_next",
    PopupMediaCaptions = "popup_media_captions",
    PopupMediaCaptionsOff = "popup_media_captions_off"
}
